weights:
  domain_target_match: 2.0
  role_family_preferred: 1.5
  remote_policy_good: 1.0
  dutch_penalty: -2.5
  skill_overlap: 0.5
  fitness_hint: 0.5
params:
  target_domains: [gov/public, construction]
  preferred_role_families: [business_analyst, solutions_consultant, product_ops]
  good_remote_policies: [remote, hybrid]
  core_skills: [sql, python, tableau, jira]


